### ISSUE TITLE
Expressão atribuir

### ISSUE THREAD

**Issue by gabrielbrandaodelima** [romildo/bcc328.2020.3#74]
#73

**Comment by gabrielbrandaodelima** [comment]
Não consegui implementar na absyntree.ml

Poderia ser? 
| AssignExp(l,r)            -> mktr "AssignExp" [tree_of_var l; tree_of_lexp r]

**Comment by romildo** [comment]
> Não consegui implementar na absyntree.ml
> 
> Poderia ser?
> | AssignExp(l,r) -> mktr "AssignExp" [tree_of_var l; tree_of_lexp r]

Só que `l` deve ser uma variável anotada com uma localização, segundo a gramática do módulo `Parser`...

**Comment by gabrielbrandaodelima** [comment]
Obrigado!
